name: Playwright Headful Matrix (20 jobs)

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL (TARGET_URL)'
        required: true
        default: 'https://example.com/'
      duration:
        description: 'Duration in seconds (DURATION)'
        required: true
        default: '20'
      concurrency:
        description: 'Tabs per job (CONCURRENCY)'
        required: true
        default: '1'
      req_per_loop:
        description: 'Requests per loop (REQ_PER_LOOP)'
        required: true
        default: '1'

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job_id: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

    env:
      # Only these 4 envs are passed into the job (as requested)
      TARGET_URL: ${{ github.event.inputs.target_url }}
      DURATION: ${{ github.event.inputs.duration }}
      CONCURRENCY: ${{ github.event.inputs.concurrency }}
      REQ_PER_LOOP: ${{ github.event.inputs.req_per_loop }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.44.0    # pin a stable version or remove pin if you prefer
          # install browser(s) for playwright
          python -m playwright install chromium

      - name: Install xvfb (allow headful on runner)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Ensure script is present and executable
        run: |
          # Put your script file at repo root (e.g. test_script.py)
          ls -lah
          chmod +x ./playwright_flood.py || true

      - name: Run Playwright script (headful via Xvfb)
        # each matrix job runs independently; use xvfb-run to provide display for headful browser
        run: |
          echo "Job #${{ matrix.job_id }} starting. TARGET_URL=$TARGET_URL"
          xvfb-run -a python ./playwright_flood.py

      - name: Upload run log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-log-job-${{ matrix.job_id }}
          path: |
            ./run.log
            ./playwright-report || true
